name: bee_wallet
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  base32: ^2.1.3
  bdk_flutter: ^0.30.0
  bip39: ^1.0.6
  blockies_ethereum: ^0.0.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  chart_sparkline: ^1.0.14
  collection: ^1.17.1
  connectivity_checker: ^1.1.0
  connectivity_plus: ^5.0.2
  convert: ^3.1.1
  cupertino_icons: ^1.0.6
  d_chart: ^2.6.3
  dart_bip32_bip44: ^0.2.0
  decimal: ^2.3.3
  dio: ^5.3.4
  dropdown_button2: ^2.3.9
  ed25519_hd_key: ^2.2.1
  encrypt: ^5.0.3
  erc20: ^1.0.1
  eth_abi_codec:
    git:
      url: https://github.com/nbltrust/dart-eth-abi-codec.git
      ref: 2.0.0
  eth_sig_util: ^0.0.9
  ethereum_addresses: ^1.0.2
  ffcache: ^1.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_inappwebview: ^5.7.2+3
  flutter_polygon: ^0.3.0+2
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.8.4
  flutter_switch: ^0.3.2
  go_router: ^12.1.1
  http: ^1.1.0
  iconify_flutter_plus: ^1.0.3
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  loading_overlay: ^0.3.0
  local_auth: ^2.1.7
  mobile_scanner: ^3.5.5
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  pin_code_fields: ^8.0.1
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.3.3
  scaffold_gradient_background: ^1.0.3+1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  solana_web3: ^0.1.3
  sui: ^0.3.1
  top_snackbar_flutter: ^3.1.0
  tron: ^0.0.2
  url_launcher: ^6.1.11
  wallet: ^0.0.13
  web3_provider: ^1.1.4
  web3dart: ^2.6.1
  web_socket_channel: ^2.4.0

dev_dependencies:
  analyzer: ^5.13.0
  build_runner: ^2.4.7
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/abi/
    - assets/logo/
    - assets/imageDapp/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/poppin/Poppins-Bold.ttf
        - asset: assets/font/poppin/Poppins-SemiBold.ttf
        - asset: assets/font/poppin/Poppins-Medium.ttf
        - asset: assets/font/poppin/Poppins-Regular.ttf
        - asset: assets/font/poppin/Poppins-Light.ttf
    - family: Roboto
      fonts:
        - asset: assets/font/roboto/Roboto-Bold.ttf
        - asset: assets/font/roboto/Roboto-Medium.ttf
        - asset: assets/font/roboto/Roboto-Regular.ttf
        - asset: assets/font/roboto/Roboto-Light.ttf
