name: bee_wallet
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  animate_do: ^4.2.0
  base32: ^2.1.3
  bip39: ^1.0.6
  blockies_ethereum: ^0.0.2
  carousel_slider: ^5.0.0
  change_app_package_name: ^1.5.0
  connectivity_plus: ^6.1.4
  convert: ^3.1.2
  cupertino_icons: ^1.0.8
  dart_bip32_bip44: ^0.2.0
  dropdown_button2: ^2.3.9
  encrypt: ^5.0.3
  erc20: ^1.0.1
  ethereum_addresses: ^1.0.2
  ffcache: ^1.1.0
  flutter:
    sdk: flutter
  flutter_polygon: ^0.3.0+2
  flutter_riverpod: ^2.6.1
  flutter_switch: ^0.3.2
  get_it: ^8.0.3
  go_router: ^15.1.1
  http: ^1.4.0
  iconify_flutter_plus: ^1.0.4
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.20.2
  isar:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  k_chart_plus_deeping: ^1.0.2-5.2.2.3
  loading_overlay: ^0.4.2
  local_auth: ^2.3.0
  mobile_scanner: ^7.0.0
  path_provider: ^2.1.5
  percent_indicator: ^4.2.5
  pin_code_fields: ^8.0.1
  pointycastle: ^3.7.4
  qr_flutter: ^4.1.0
  reown_walletkit: ^1.2.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  simple_gradient_text: ^1.3.0
  top_snackbar_flutter: ^3.2.0
  url_launcher: ^6.3.1
  web3_webview: ^1.0.7
  web3dart: ^2.7.3
  web_socket_channel: ^3.0.3
  webview_flutter: ^4.11.0

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  isar_generator:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/abi/
    - assets/logo/
    - assets/imageDapp/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/poppin/Poppins-Bold.ttf
        - asset: assets/font/poppin/Poppins-SemiBold.ttf
        - asset: assets/font/poppin/Poppins-Medium.ttf
        - asset: assets/font/poppin/Poppins-Regular.ttf
        - asset: assets/font/poppin/Poppins-Light.ttf
    - family: Roboto
      fonts:
        - asset: assets/font/roboto/Roboto-Bold.ttf
        - asset: assets/font/roboto/Roboto-Medium.ttf
        - asset: assets/font/roboto/Roboto-Regular.ttf
        - asset: assets/font/roboto/Roboto-Light.ttf
